import { Inter } from 'next/font/google';
import Link from 'next/link';
import Head from 'next/head';
import Script from 'next/script';
import './globals.css';
import styles from './layout.module.css';  // Import the styles

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'NextGameCollection',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <Head>
        <link rel="icon" href="/favicon.ico" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
      <Script
        src="https://www.googletagmanager.com/gtag/js?id=G-7LY4HN3ZPV"
        strategy="afterInteractive"
      />
      <Script id="google-analytics" strategy="afterInteractive">
        {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', 'G-7LY4HN3ZPV');
        `}
      </Script>
      <body>
        <div className={styles.layout}>
          <header className={styles.header}>
            <nav>
              <ul className={styles.headerLinks}>
                <li><Link href="/">ゲーム</Link></li>
                <li><Link href="/about">このサイトについて</Link></li>
                <li><Link href="/contact">お問い合わせ</Link></li>
              </ul>
            </nav>
          </header>
          {children}
          <footer className={styles.footer}>
            <a href="https://twitter.com/R_engineer69" target="_blank" rel="noopener noreferrer">
              <h2>© 2023 RYOSUKE@エンジニア</h2>
            </a>
          </footer>
        </div>
      </body>
    </html>
  );
}
