import { Inter } from 'next/font/google';
import Link from 'next/link';
import './globals.css';
import styles from './layout.module.css';  // Import the styles

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'NextGameCollection',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <head>
        <link rel="icon" href="/favicon.ico"></link>
      </head>
      <body>
        <div className={styles.layout}>
          <header className={styles.header}>
            <nav>
              <ul className={styles.headerLinks}>
                <li><Link href="/">ゲーム</Link></li>
                <li><Link href="/about">このサイトについて</Link></li>
                <li><Link href="/contact">お問い合わせ</Link></li>
              </ul>
            </nav>
          </header>
          {children}
          <footer className={styles.footer}>
            <a href="https://twitter.com/R_engineer69" target="_blank" rel="noopener noreferrer">
              <h2>© 2023 RYOSUKE@エンジニア</h2>
            </a>
          </footer>
        </div>
      </body>
    </html>
  );
}
